[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "minecraft-data-platform"
version = "0.1.0"

dependencies = [
    "duckdb",
    "polars",
    "pandas",
    "pyarrow",
    "httpx",
    "pyyaml",
    "streamlit",
    "plotly",
    "jupyter",
    "ipykernel",
    "nbconvert",
    "tldextract",
    "dbt-core==1.11.11",
    "dbt-duckdb==1.11.0",
    "duckdb==1.5.5",
]

[tool.setuptools.packages.find]
where = ["."]
include = [
    "shared_code*",
    "pipelines*",
    "minecraft_data_dashboard*"
]