minecraft_data_platform:

  target: dev

  outputs:

    dev:
      type: duckdb

      path: /Users/admin/AroTekCodingSpace/Python-Workspace/Minecraft-Data-Platform/data/silver/dev/api_modrinth_com.duckdb


      threads: 1
      settings:
        memory_limit: "14GB"
        preserve_insertion_order: false

      attach:
        - path: /Users/admin/AroTekCodingSpace/Python-Workspace/Minecraft-Data-Platform/data/bronze/dev/api_modrinth_com.duckdb
          alias: bronze
          read_only: true